### ISSUE TITLE
Could Not Open 1 file "hg38.d14.cdx"

### ISSUE THREAD

**Issue by yubau1112** [wingolab-org/mpd-perl#8]
git clone https://bitbucket.org/wingolab/mpd-dat.git

and

my config.yaml is:

---
BedFile: markers.txt.bed
isPcrBinary: /home/yubau/bin/x86_64/isPcr
TwoBitFile: hg38.2bit
MpdBinary: mpd-c/bin/mpd
MpdIdx: mpd-dat/hg38/hg38.d14.sdx
dbSnpIdx: mpd-dat/ds_flat/ds_flat.sdx

CoverageThreshold: 0.8
PrimerSizeMin: 17
PrimerSizeMax: 27
PadSize: 60
PoolMax: 10
PoolMin: 5

AmpSizeMax: 260
AmpSizeMin: 230
TmMax: 62
TmMin: 57
GcMax: 0.7
GcMin: 0.3

Iter: 2
IncrTm: 1
IncrTmStep: 1
IncrAmpSize: 10

my command is :
perl design.pl -a -b markers.txt.bed -c config.yaml -d test -o test.txt

than I got:
Could Not Open 1 file "hg38.d14.cdx"

What can I do?

thanks

**Comment by wingolab** [comment]
Can you verify that mpd-dat/hg38 contains a genomic index? For instance, I'd expect it might contain the content from: https://bitbucket.org/wingolab/mpd-dat/

**Comment by yubau1112** [comment]
I git clone https://bitbucket.org/wingolab/mpd-dat.git
so 
mpd-dat dir file have same with https://bitbucket.org/wingolab/mpd-dat/

-rw-rw-r-- 1 yubau yubau 128M Mar 17 17:11 hg38.d14.15x
-rw-rw-r-- 1 yubau yubau 740M Mar 17 17:11 hg38.d14.cdx
-rw-rw-r-- 1 yubau yubau 1.4G Mar 17 17:11 hg38.d14.idx
-rw-rw-r-- 1 yubau yubau  13K Mar 17 17:11 hg38.d14.in
-rw-rw-r-- 1 yubau yubau  31M Mar 17 17:11 hg38.d14.rdx
-rw-rw-r-- 1 yubau yubau 5.5K Mar 17 17:11 hg38.d14.sdx

Can you re index genome and used mpd to check hg38.d14 can work than reupload to https://bitbucket.org/wingolab/mpd-dat/? 

**or** 

Can you tell me what is you used parameter for index_genome?

I download a new hg38.fa file from UCSC
and run index_genome

Send Output to Screen or Disk? [S,D]
S
Number of Contig Fasta Files to Process
1
Please Enter Name For Contig Fasta File 1
hg38.fa
Basename to save compressed Genome and Indexes
hg38
Maximum Number Of Sites in a contig
100000
Index Depth
100000

but I want to use your  parameter for index_genome

thanks!

oh I change path now!

BedFile: markers.txt.bed
isPcrBinary: /home/yubau/bin/x86_64/isPcr
TwoBitFile: hg38.2bit
MpdBinary: mpd-c/bin/mpd
**MpdIdx: mpd-dat/hg38.d14.sdx
dbSnpIdx: mpd-dat/ds_flat.sdx**

but still get "Could Not Open 1 file "hg38.d14.cdx""

**Comment by yubau1112** [comment]
I move all "git clone https://bitbucket.org/wingolab/mpd-dat.git" file to same with "design.pl" file directory

AND it's can work!

ask a question


my $m = MPD->new_with_config(
  {
    configfile  => $config_file,
    BedFile     => 'target_regions.bed',
    OutExt      => 'myGreatPrimerPools',
    OutDir      => '/temp/',
    InitTmMin   => 58,
    InitTmMax   => 61,
    PoolMin     => 5,
    Debug       => 0,
    IterMax     => 2,
    **RunIsPcr    => undef**, # set to something perl evaluates to true if you want isPcr to check the in-silico PCR
    Act         => 1,     # set to something perl evaluates to true if you want the program to execute the mpd-c binary
    ProjectName => $out_ext,
    FwdAdapter  => '',    # your fwd adapter
    RevAdapter  => '',    # your rev adapter
    Offset      => 0,     # when printing pools where do we start?
    Randomize   => 1,     # should we shuffle the pools so they are in random order?
  }
);


if I want to RunIsPcr, I just need to change "RunIsPcr    => undef" to "RunIsPcr    => 1"?

thank you so much!

**Comment by zyh2016** [comment]
I have the same question...
